from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time
driver=webdriver.Chrome()

driver.get("https://www.demoblaze.com/index.html")
driver.maximize_window()
driver.find_element(By.XPATH,'//*[@id="signin2"]').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="sign-username"]').send_keys("ext382")
driver.find_element(By.XPATH,'//*[@id="sign-password"]').send_keys("Hello*2025")
driver.find_element(By.XPATH,'//*[@id="signInModal"]/div/div/div[3]/button[2]').click()
time.sleep(5)
driver.find_element(By.XPATH,'//*[@id="login2"]').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="loginusername"]').send_keys("ext382")
driver.find_element(By.XPATH,'//*[@id="loginpassword"]').send_keys("Hello*2025")
driver.find_element(By.XPATH,'//*[@id="logInModal"]/div/div/div[3]/button[2]').click()
time.sleep(5)
driver.find_element(By.XPATH,'//*[@id="navbarExample"]/ul/li[2]/a').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="recipient-email"]').send_keys("testadmin25@gmail.com")
driver.find_element(By.XPATH,'//*[@id="recipient-name"]').send_keys("9876543210")
driver.find_element(By.XPATH,'//*[@id="message-text"]').send_keys("This is the test message ")
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="exampleModal"]/div/div/div[3]/button[2]').click()
time.sleep(7)
driver.find_element(By.XPATH,'//*[@id="navbarExample"]/ul/li[4]/a').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="page-wrapper"]/div/div[2]/button').click()
time.sleep(8)
driver.find_element(By.XPATH,'//*[@id="name"]').send_keys("DELL")
driver.find_element(By.XPATH,'//*[@id="country"]').send_keys("USA")
driver.find_element(By.XPATH,'//*[@id="city"]').send_keys("Ohaio")
driver.find_element(By.XPATH,'//*[@id="card"]').send_keys("256412345623")
driver.find_element(By.XPATH,'//*[@id="month"]').send_keys("October")
driver.find_element(By.XPATH,'//*[@id="year"]').send_keys("2025")
driver.find_element(By.XPATH,'//*[@id="orderModal"]/div/div/div[3]/button[2]').click()
time.sleep(5)
driver.find_element(By.XPATH,'/html/body/div[10]/div[7]/div/button').click()
time.sleep(8)
driver.find_element(By.XPATH,'//*[@id="logout2"]').click()
time.sleep(10)
driver.close
